apiVersion: v1
kind: Service
metadata:
  name: ca0-org2
  namespace: fabric-net
  labels:
    k8s-app: ca0-org2
spec:
  ports:
  - name: "7054"
    port: 7054
    targetPort: 7054
  selector:
    k8s-app: ca0-org2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ca0-org2
  namespace: fabric-net
  labels:
    k8s-app: ca0-org2
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ca0-org2
  template:
    metadata:
      labels:
        k8s-app: ca0-org2
    spec:
      containers:
      - args:
        - sh
        - -c
        - fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca0-org2.fabric-net.svc.cluster.local-cert.pem
          --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b
          admin:adminpw -d
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca0-org2
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /etc/hyperledger/fabric-ca-server-config/ca0-org2.fabric-net.svc.cluster.local-cert.pem
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
        - name: GODEBUG
          value: netdns=go
        image: hyperledger/fabric-ca:latest
        imagePullPolicy: Never
        name: ca0-org2
        ports:
        - containerPort: 7054
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric-ca-server-config
          name: ca
      restartPolicy: Always
      volumes:
      - name: ca
        hostPath:
          path: /var/fabric-net/crypto-config/peerOrganizations/org2.fabric-net.svc.cluster.local/ca/
      nodeSelector:
        bc: "true"

